name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache commit message
      run: |
        git log -n1 --pretty=%B ${{ github.sha }}

    - uses: actions/setup-python@v3

    - uses: pre-commit/action@v3.0.0
