name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{github.event.after}}
    - run: |
        git log --format=%B -n 1 ${{github.event.after}} > commit_msg
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --commit-msg-filename=commit_msg
    - run: |
        pip install pre-commit
        pre-commit run --all
