name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - run: |
        git log --pretty=%B -1 ${{ github.head_ref }}
    - uses: actions/setup-python@v3
    - name: Generate fake commit message
      run: |
        echo "ci: a fine message">commit_msg
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --commit-msg-filename=commit_msg
    - run: |
        pip install pre-commit
        pre-commit run --all
